<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\ProjectBuildProperties.targets" />
	
	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<LangVersion>12.0</LangVersion>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<PathMap>$(MSBuildProjectDirectory)=$(MSBuildProjectName)</PathMap>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FFmpegArgs.Filters.Multimedia" Version="2.2.0" />
		<PackageReference Include="FFmpegArgs.Filters.VideoFilters" Version="2.2.0" />
	</ItemGroup>
</Project>
