<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-windows7.0</TargetFrameworks>
		<LangVersion>12.0</LangVersion>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<PathMap>$(MSBuildProjectDirectory)=$(MSBuildProjectName)</PathMap>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FFmpegArgs" Version="2.2.0" />
		<PackageReference Include="FFmpegArgs.Codec" Version="2.2.0" />
		<PackageReference Include="FFmpegArgs.Cores" Version="2.2.0" />
		<PackageReference Include="FFmpegArgs.Executes" Version="2.2.0" />
		<PackageReference Include="FFmpegArgs.Extensions" Version="2.2.0" />
		<PackageReference Include="FFmpegArgs.Filters" Version="2.2.0" />
		<PackageReference Include="FFmpegArgs.Filters.AudioFilters" Version="2.2.0" />
		<PackageReference Include="FFmpegArgs.Filters.AudioSources" Version="2.2.0" />
		<PackageReference Include="FFmpegArgs.Filters.Multimedia" Version="2.2.0" />
		<PackageReference Include="FFmpegArgs.Filters.OpenCLVideoFilters" Version="2.2.0" />
		<PackageReference Include="FFmpegArgs.Filters.VideoFilters" Version="2.2.0" />
		<PackageReference Include="FFmpegArgs.Filters.VideoSources" Version="2.2.0" />
		<PackageReference Include="FFmpegArgs.Inputs" Version="2.2.0" />
		<PackageReference Include="FFmpegArgs.Outputs" Version="2.2.0" />
		
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.2" />
		<PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
		<PackageReference Include="MSTest.TestFramework" Version="2.2.10" />
		<PackageReference Include="coverlet.collector" Version="3.1.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\TqkLibrary.FFmpegTransition\TqkLibrary.FFmpegTransition.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Resources\*.*">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
